packages:
  - 'backend/services/api-gateway'
  - 'backend/services/api-server'
  - 'backend/services/database-service'
  - 'backend/services/file-server'
  - 'backend/services/workers/pdf-worker'
  - 'backend/shared'
  - 'frontend'
  - 'mockserver'