import * as fs from 'fs';

export const convertToNetscapeCookie = (
  loadpath: string,
  domain = 'mebbisyd.meb.gov.tr',
) => {
  const savepath = loadpath + '.netscape.txt';
  const cookieString = fs.readFileSync(loadpath, 'utf8');

  const cookies = cookieString.split(';');
  const cookieObj: { [key: string]: string } = {};
  const ignoreKeys = ['path', 'HttpOnly', 'SameSite'];

  for (const cookie of cookies) {
    const [key, value] = cookie.split('=');
    if (!value || ignoreKeys.indexOf(key.trim()) > -1) continue;
    cookieObj[key.trim()] = value.trim();
  }

  const lines = [
    '# Netscape HTTP Cookie File',
    '# https://curl.se/docs/http-cookies',
    '# This file was generated by libcurl! Edit at your own risk.',
    '',
  ];

  for (const key in cookieObj) {
    lines.push(
      `#HttpOnly_${domain}\tFALSE\t/\tFALSE\t0\t${key}\t${cookieObj[key]}`,
    );
  }

  fs.writeFileSync(savepath, lines.join('\n'), 'utf8');
};
