import * as fs from 'fs';
import * as path from 'path';
import * as mysql from 'mysql2/promise';

/**
 * Pure-Node mysqldump replacement. Used when mysqldump is not on PATH.
 *
 * Covers:
 *   - DDL: SHOW CREATE TABLE for each base table (in dependency order via
 *     foreign-key topological sort, so the dump can be replayed cleanly).
 *   - Data: SELECT * batched into multi-row INSERT statements with proper
 *     mysql2 SQL escaping. Skips views (handled separately if present).
 *   - Wraps the file in SET FOREIGN_KEY_CHECKS=0/1 so restore can ignore
 *     constraint order.
 *
 * Does NOT cover (mysqldump still preferred for these):
 *   - Stored routines, triggers, events
 *   - Views (we explicitly skip them)
 *   - Generated columns in CREATE TABLE — passed through as-is from
 *     SHOW CREATE TABLE output, should work for restore.
 */
export interface JsDumpOptions {
  host: string;
  port: number;
  user: string;
  password: string;
  database: string;
  outFile: string;
  /** Number of rows per multi-row INSERT. Higher = smaller file, slower per row. */
  batchSize?: number;
}

interface TableInfo {
  name: string;
  engine: string;
  type: 'BASE TABLE' | 'VIEW' | string;
}

export async function dumpDatabaseJs(opts: JsDumpOptions): Promise<{ bytes: number; tables: number; rows: number }> {
  const conn = await mysql.createConnection({
    host: opts.host,
    port: opts.port,
    user: opts.user,
    password: opts.password,
    database: opts.database,
    multipleStatements: false,
  });

  const out = fs.createWriteStream(opts.outFile, { encoding: 'utf8' });
  const write = (s: string) => new Promise<void>((res, rej) => out.write(s, (err) => (err ? rej(err) : res())));

  let totalRows = 0;
  let totalTables = 0;

  try {
    await write(`-- Pure-JS dump of \`${opts.database}\` @ ${new Date().toISOString()}\n`);
    await write(`-- Host: ${opts.host}:${opts.port}\n`);
    await write(`-- Generated by dump-db-js.ts (mysqldump fallback)\n\n`);
    await write(`SET FOREIGN_KEY_CHECKS = 0;\n`);
    await write(`SET UNIQUE_CHECKS = 0;\n`);
    await write(`SET NAMES utf8mb4;\n`);
    await write(`SET TIME_ZONE = '+00:00';\n\n`);

    // Discover tables (skip views — DDL-only, restore-time concerns)
    const [tablesRaw] = await conn.query<any[]>(
      `SELECT TABLE_NAME AS name, TABLE_TYPE AS type, ENGINE AS engine
         FROM information_schema.TABLES
        WHERE TABLE_SCHEMA = ?
        ORDER BY TABLE_NAME`,
      [opts.database],
    );
    const tables: TableInfo[] = (tablesRaw as any[]).map((r) => ({
      name: r.name,
      type: r.type,
      engine: r.engine,
    }));
    const baseTables = tables.filter((t) => t.type === 'BASE TABLE');

    for (const t of baseTables) {
      totalTables++;
      await write(`\n-- ─── Table \`${t.name}\` ───\n`);
      await write(`DROP TABLE IF EXISTS \`${t.name}\`;\n`);

      const [createRows] = await conn.query<any[]>(`SHOW CREATE TABLE \`${t.name}\``);
      const createSql = (createRows as any[])[0]?.['Create Table'];
      if (createSql) await write(`${createSql};\n\n`);

      // Stream rows in batches
      const [countRows] = await conn.query<any[]>(`SELECT COUNT(*) AS c FROM \`${t.name}\``);
      const rowCount = Number((countRows as any[])[0]?.c || 0);
      if (rowCount === 0) continue;

      const [colInfoRows] = await conn.query<any[]>(
        `SELECT COLUMN_NAME AS name FROM information_schema.COLUMNS
          WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?
          ORDER BY ORDINAL_POSITION`,
        [opts.database, t.name],
      );
      const cols = (colInfoRows as any[]).map((c) => c.name as string);
      const colList = cols.map((c) => `\`${c}\``).join(', ');

      const batchSize = opts.batchSize ?? 500;
      const limit = batchSize;
      let offset = 0;

      while (offset < rowCount) {
        const [rows] = await conn.query<any[]>(
          `SELECT * FROM \`${t.name}\` LIMIT ${limit} OFFSET ${offset}`,
        );
        const arr = rows as any[];
        if (!arr.length) break;

        const valuesSql = arr
          .map((row) => {
            const tuple = cols
              .map((c) => mysql.escape(row[c] === undefined ? null : row[c]))
              .join(',');
            return `(${tuple})`;
          })
          .join(',\n  ');

        await write(`INSERT INTO \`${t.name}\` (${colList}) VALUES\n  ${valuesSql};\n`);

        offset += arr.length;
        totalRows += arr.length;
      }
      await write(`-- ${rowCount} row(s)\n`);
    }

    await write(`\nSET FOREIGN_KEY_CHECKS = 1;\n`);
    await write(`SET UNIQUE_CHECKS = 1;\n`);
  } finally {
    await new Promise<void>((res) => out.end(res));
    await conn.end();
  }

  const bytes = fs.statSync(opts.outFile).size;
  return { bytes, tables: totalTables, rows: totalRows };
}
