import { AdminDrivingSchoolsService } from './admin-driving-schools.service';
import { CreateDrivingSchoolDto, UpdateDrivingSchoolDto } from './dto';
export declare class AdminDrivingSchoolsController {
    private readonly service;
    constructor(service: AdminDrivingSchoolsService);
    getAllDrivingSchools(): Promise<{
        subscription_id: number;
        name: string;
        address: string;
        phone: string;
        mebbis_username?: string;
        mebbis_password?: string;
        mebbis_credentials_locked: boolean;
        manager_id: number;
        owner_id: number;
        city_id?: number;
        district_id?: number;
        created_by?: number;
        students: import("@surucukursu/shared").DrivingSchoolStudentEntity[];
        cars: import("@surucukursu/shared").DrivingSchoolCarEntity[];
        manager: import("@surucukursu/shared").DrivingSchoolManagerEntity;
        owner: import("@surucukursu/shared").DrivingSchoolOwnerEntity;
        city: import("@surucukursu/shared").CityEntity;
        district: import("@surucukursu/shared").DistrictEntity;
        settings: import("@surucukursu/shared").DrivingSchoolSettingsEntity;
        subscription: import("@surucukursu/shared").SubscriptionEntity;
        id: number;
        created_at: number;
        updated_at: number;
        deleted_at?: number | null;
    }[]>;
    getDrivingSchoolById(id: string): Promise<{
        subscription_id: number;
        name: string;
        address: string;
        phone: string;
        mebbis_username?: string;
        mebbis_password?: string;
        mebbis_credentials_locked: boolean;
        manager_id: number;
        owner_id: number;
        city_id?: number;
        district_id?: number;
        created_by?: number;
        students: import("@surucukursu/shared").DrivingSchoolStudentEntity[];
        cars: import("@surucukursu/shared").DrivingSchoolCarEntity[];
        manager: import("@surucukursu/shared").DrivingSchoolManagerEntity;
        owner: import("@surucukursu/shared").DrivingSchoolOwnerEntity;
        city: import("@surucukursu/shared").CityEntity;
        district: import("@surucukursu/shared").DistrictEntity;
        settings: import("@surucukursu/shared").DrivingSchoolSettingsEntity;
        subscription: import("@surucukursu/shared").SubscriptionEntity;
        id: number;
        created_at: number;
        updated_at: number;
        deleted_at?: number | null;
    }>;
    createDrivingSchool(dto: CreateDrivingSchoolDto, req: any): Promise<{
        subscription_id: number;
        subscription: {
            id: number;
            type: string;
            pdf_print_limit: number;
            pdf_print_used: number;
            created_at: number;
            updated_at: number;
            ends_at: number;
        };
        name: string;
        address: string;
        phone: string;
        mebbis_username?: string;
        mebbis_password?: string;
        mebbis_credentials_locked: boolean;
        manager_id: number;
        owner_id: number;
        city_id?: number;
        district_id?: number;
        created_by?: number;
        students: import("@surucukursu/shared").DrivingSchoolStudentEntity[];
        cars: import("@surucukursu/shared").DrivingSchoolCarEntity[];
        manager: import("@surucukursu/shared").DrivingSchoolManagerEntity;
        owner: import("@surucukursu/shared").DrivingSchoolOwnerEntity;
        city: import("@surucukursu/shared").CityEntity;
        district: import("@surucukursu/shared").DistrictEntity;
        settings: import("@surucukursu/shared").DrivingSchoolSettingsEntity;
        id: number;
        created_at: number;
        updated_at: number;
        deleted_at?: number | null;
    }>;
    updateDrivingSchool(id: string, dto: UpdateDrivingSchoolDto, req: any): Promise<{
        subscription_id: any;
        subscription: {
            id: any;
            type: any;
            pdf_print_limit: any;
            pdf_print_used: any;
            created_at: any;
            updated_at: any;
            ends_at: any;
        };
        name: string;
        address: string;
        phone: string;
        mebbis_username?: string;
        mebbis_password?: string;
        mebbis_credentials_locked: boolean;
        manager_id: number;
        owner_id: number;
        city_id?: number;
        district_id?: number;
        created_by?: number;
        students: import("@surucukursu/shared").DrivingSchoolStudentEntity[];
        cars: import("@surucukursu/shared").DrivingSchoolCarEntity[];
        manager: import("@surucukursu/shared").DrivingSchoolManagerEntity;
        owner: import("@surucukursu/shared").DrivingSchoolOwnerEntity;
        city: import("@surucukursu/shared").CityEntity;
        district: import("@surucukursu/shared").DistrictEntity;
        settings: import("@surucukursu/shared").DrivingSchoolSettingsEntity;
        id: number;
        created_at: number;
        updated_at: number;
        deleted_at?: number | null;
    }>;
    deleteDrivingSchool(id: string, req: any): Promise<{
        message: string;
    }>;
    loginAs(code: string): Promise<{
        token: string;
        user: {
            id: number;
            email: string;
            name: string;
            userType: import("../../auth/dto/enum").UserTypes;
            school: {
                id: number;
                name: string;
                subscription: import("@surucukursu/shared").SubscriptionEntity;
            };
        };
    }>;
}
