import { JwtService } from '@nestjs/jwt';
import { Repository } from 'typeorm';
import { DrivingSchoolEntity, SubscriptionEntity, SystemLogsEntity, SessionEntity, DrivingSchoolStudentEntity, DrivingSchoolCarEntity } from '@surucukursu/shared';
import { UserTypes } from '../../auth/dto/enum';
import { CreateDrivingSchoolDto, UpdateDrivingSchoolDto } from './dto';
export declare class AdminDrivingSchoolsService {
    private readonly schoolRepository;
    private readonly subscriptionRepository;
    private readonly systemLogsRepository;
    private readonly sessionRepository;
    private readonly studentRepository;
    private readonly carRepository;
    private jwtService;
    constructor(schoolRepository: Repository<DrivingSchoolEntity>, subscriptionRepository: Repository<SubscriptionEntity>, systemLogsRepository: Repository<SystemLogsEntity>, sessionRepository: Repository<SessionEntity>, studentRepository: Repository<DrivingSchoolStudentEntity>, carRepository: Repository<DrivingSchoolCarEntity>, jwtService: JwtService);
    getAllDrivingSchools(): Promise<{
        subscription_id: number;
        name: string;
        address: string;
        phone: string;
        mebbis_username?: string;
        mebbis_password?: string;
        mebbis_credentials_locked: boolean;
        manager_id: number;
        owner_id: number;
        city_id?: number;
        district_id?: number;
        created_by?: number;
        students: DrivingSchoolStudentEntity[];
        cars: DrivingSchoolCarEntity[];
        manager: import("@surucukursu/shared").DrivingSchoolManagerEntity;
        owner: import("@surucukursu/shared").DrivingSchoolOwnerEntity;
        city: import("@surucukursu/shared").CityEntity;
        district: import("@surucukursu/shared").DistrictEntity;
        settings: import("@surucukursu/shared").DrivingSchoolSettingsEntity;
        subscription: SubscriptionEntity;
        id: number;
        created_at: number;
        updated_at: number;
        deleted_at?: number | null;
    }[]>;
    getDrivingSchoolById(id: number): Promise<{
        subscription_id: number;
        name: string;
        address: string;
        phone: string;
        mebbis_username?: string;
        mebbis_password?: string;
        mebbis_credentials_locked: boolean;
        manager_id: number;
        owner_id: number;
        city_id?: number;
        district_id?: number;
        created_by?: number;
        students: DrivingSchoolStudentEntity[];
        cars: DrivingSchoolCarEntity[];
        manager: import("@surucukursu/shared").DrivingSchoolManagerEntity;
        owner: import("@surucukursu/shared").DrivingSchoolOwnerEntity;
        city: import("@surucukursu/shared").CityEntity;
        district: import("@surucukursu/shared").DistrictEntity;
        settings: import("@surucukursu/shared").DrivingSchoolSettingsEntity;
        subscription: SubscriptionEntity;
        id: number;
        created_at: number;
        updated_at: number;
        deleted_at?: number | null;
    }>;
    createDrivingSchool(dto: CreateDrivingSchoolDto, adminId: number): Promise<{
        subscription_id: number;
        subscription: {
            id: number;
            type: string;
            pdf_print_limit: number;
            pdf_print_used: number;
            created_at: number;
            updated_at: number;
            ends_at: number;
        };
        name: string;
        address: string;
        phone: string;
        mebbis_username?: string;
        mebbis_password?: string;
        mebbis_credentials_locked: boolean;
        manager_id: number;
        owner_id: number;
        city_id?: number;
        district_id?: number;
        created_by?: number;
        students: DrivingSchoolStudentEntity[];
        cars: DrivingSchoolCarEntity[];
        manager: import("@surucukursu/shared").DrivingSchoolManagerEntity;
        owner: import("@surucukursu/shared").DrivingSchoolOwnerEntity;
        city: import("@surucukursu/shared").CityEntity;
        district: import("@surucukursu/shared").DistrictEntity;
        settings: import("@surucukursu/shared").DrivingSchoolSettingsEntity;
        id: number;
        created_at: number;
        updated_at: number;
        deleted_at?: number | null;
    }>;
    updateDrivingSchool(id: number, dto: UpdateDrivingSchoolDto, adminId: number): Promise<{
        subscription_id: any;
        subscription: {
            id: any;
            type: any;
            pdf_print_limit: any;
            pdf_print_used: any;
            created_at: any;
            updated_at: any;
            ends_at: any;
        };
        name: string;
        address: string;
        phone: string;
        mebbis_username?: string;
        mebbis_password?: string;
        mebbis_credentials_locked: boolean;
        manager_id: number;
        owner_id: number;
        city_id?: number;
        district_id?: number;
        created_by?: number;
        students: DrivingSchoolStudentEntity[];
        cars: DrivingSchoolCarEntity[];
        manager: import("@surucukursu/shared").DrivingSchoolManagerEntity;
        owner: import("@surucukursu/shared").DrivingSchoolOwnerEntity;
        city: import("@surucukursu/shared").CityEntity;
        district: import("@surucukursu/shared").DistrictEntity;
        settings: import("@surucukursu/shared").DrivingSchoolSettingsEntity;
        id: number;
        created_at: number;
        updated_at: number;
        deleted_at?: number | null;
    }>;
    deleteDrivingSchool(id: number, adminId: number): Promise<{
        message: string;
    }>;
    loginAs(code: string): Promise<{
        token: string;
        user: {
            id: number;
            email: string;
            name: string;
            userType: UserTypes;
            school: {
                id: number;
                name: string;
                subscription: SubscriptionEntity;
            };
        };
    }>;
}
